
name: Reminder Deployment Pipeline

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [dev]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          script: |
            cd /var/www/zc_plugin_reminder/
            git stash
            git pull
            yarn run holoInstall
            yarn run build
            pm2 start reminders_plugin
